name: baryabest_app
description: BaryaBest affiliate app frontend
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.4.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/baryabest_logo.png"
  adaptive_icon_background: "#081029"
  adaptive_icon_foreground: "assets/images/baryabest_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
